---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    tgsmtp_molecule_root: /tmp/tgsmtp-molecule
    tgsmtp_role_path: >-
      {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') |
      default(playbook_dir ~ '/../..', true) }}
    tgsmtp_script_source: >-
      {{ lookup('env', 'TGSMTP_SCRIPT_URL') |
      default('file://' ~ playbook_dir ~ '/../../../tgsmtp/tgsmtp.py', true) }}
  roles:
    - role: "{{ tgsmtp_role_path }}"
      vars:
        tgsmtp_telegram_token: "{{ lookup('env', 'TGSMTP_TEST_TOKEN') | default('molecule-token', true) }}"
        tgsmtp_telegram_chat_id: "{{ lookup('env', 'TGSMTP_TEST_CHAT_ID') | default('-1000000000000', true) }}"
        tgsmtp_install_path: "{{ tgsmtp_molecule_root }}/bin/tgsmtp"
        tgsmtp_alias_path: "{{ tgsmtp_molecule_root }}/sbin/sendmail"
        tgsmtp_alias_unicode: true
        tgsmtp_log_path: "{{ tgsmtp_molecule_root }}/log/tgsmtp.log"
        tgsmtp_logrotate_install: false
        tgsmtp_script_url: "{{ tgsmtp_script_source }}"
